import modules.lyrics as lyrics

# google
string = "All my life I've been searching for something Something never comes never leads to nothing Nothing satisfies but I'm getting close Closer to the prize at the end of the rope All night long I dream of the day When it comes around and it's taken away Leaves me with the feeling that I feel the most Feel it come to life when I see your ghost Calm down don't you resist You've such a delicate wrist And if I give it a twist Something to hold when I lose my grip Will I find something in there To give me just what I need? Another reason to bleed One by one hidden up my sleeve One by one hidden up my sleeve Don't let it go to waste, I love it but I hate the taste Weight keepin' me down Don't let it go to waste, I love it but I hate the taste Weight keepin' me down Will I find a believer? Another one who believes Another one to deceive Over and over down on my knees If I get any closer And if you open up wide And if you let me inside On and on I've got nothing to hide On and on I've got nothing to hide Don't let it go to waste, I love it but I hate the taste Weight keepin' me down Don't let it go to waste, I love it but I hate the taste Weight keepin' me down All my life I've been searching for something Something never comes never leads to nothing Nothing satisfies but I'm getting close Closer to the prize at the end of the rope All night long I dream of the day When it comes around and it's taken away Leaves me with the feeling that I feel the most Feel it come to life when I see your ghost Then I'm done, done, on to the next one Done, done and I'm on to the next one Done, done and I'm on to the next one Done, done and I'm on to the next one Done, done and I'm on to the next one Done, done and I'm on to the next one Done, done and I'm on to the next one Done, I'm done and I'm on to the next Done, done, on to the next one Done, I'm done and on to the next one Done, done, on to the next one Done, I'm done and I'm on to the next Don't let it go to waste, I love it but I hate the taste Weight keepin' me down Don't let it go to waste, I love it but I hate the taste Weight keepin' me down Done, done, on to the next one Done, I'm done and I'm on to the next"

# From lyrics api
string2 = "All my life I've been searching for something\r\nSomething never comes, never leads to nothing\r\nNothing satisfies, but I'm getting close\r\n\nCloser to the prize at the end of the rope\r\nAll night long I dream of the day\r\nWhen it comes around and it's taken away\n\nLeaves me with the feeling that I feel the most\n\nFeel it come to life when I see your ghost \n\nCalm down, don't you resist\n\nYou've such a delicate wrist\n\nAnd if I give it a twist\n\nSomething to hold when I lose my grip\n\nWill I find something in there?\n\nTo give me just what I need\n\nAnother reason to bleed\n\nOne by one hidden up my sleeve x2\n\n\n\n(chorus)\n\nHey don't let it go to waste\n\nI love it but I hate the taste\n\nWeight, keeping me down) x2\n\n\n\nWill I find a believer?\n\nAnother one who believes\n\nAnother one to deceive\n\nOver and over down on my knees\n\nIf I get any closer\n\nAnd if you open up wide\n\nAnd if you let me inside\n\nOn and on I got nothing to hide x2\n\n\n\n(chorus)x2\n\n\n\nAll my life I've been searching for something\n\nSomething never comes, never leads to nothing\n\nNothing satisfies, but I'm getting close\n\nCloser to the prize at the end of the rope\n\nAll night long I dream of the day\n\nWhen it comes around and it's taken away\n\nLeaves me with the feeling that I feel the most\n\nFeel it come to life when I see your ghost\n\nThen I'm done done, on to the next one\n\nDone done, and I'm on to the next one x6\n\nDone I'm done and I'm on to the next\n\nDone done on to the next one\n\nDone I'm done and I'm on to the next one\n\nDone done on to the next one\n\nDone I'm done and I'm on to the next\n\n\n\n(chorus)x2\n\n\n\nDone done on to the next one\n\nDone I'm done and I'm on to the next"

# From lyrics api 5 seconds after
string3 = "All my life I’ve been searching for somethin’\nSomethin’ never comes, never leads to nothin’\nNothin’ satisfies, but I’m getting close\nCloser to the prize at the end of the rope\n\nAll night long I dream of the day\nWhen it comes around and it’s taken away\nLeaves me with the feeling that I feel the most\nFeel it come to life when I see your ghost\n\nCome down, don’t you resist\nYou have such a delicate wrist \nAnd if I give it a twist\nSomething to hold when I lose my grip\n\nWill I find something in there\nTo give me just what I need\nAnother reason to bleed\nOne by one hidden up my sleeve\nOne by one hidden up my sleeve\n\nHey, don’t let it go to waste\nI love it but I hate the taste\nWeight keeping me down\n\nHey, don’t let it go to waste\nI love it but I hate the taste\nWeight keeping me down\n\nWill I find a believer?\nAnother one who believes\nAnother one to deceive\nOver and over down on my knees\n\nIf I get any closer\nAnd if you open up wide\nAnd if you let me inside\nOn and on, I got nothing to hide\nOn and on, I got nothing to hide\n\nHey, don't let it go to waste\nI love it but I hate the taste\nWeight keeping me down\n\nHey, don’t let it go to waste\nI love it but I hate the taste\nWeight keeping me down\n\nAll my life I’ve been searching for something\nSomething never comes, never leads to nothin’\nNothin’ satisfies, but I’m getting close\nCloser to the prize at the end of the rope\n\nAll night long I dream of the day\nWhen it comes around and it’s taken away\nLeaves me with the feelin' that I feel the most\nFeel it come to life when I see your ghost\n\nThen I’m done, done onto the next one\nDone, done and I’m onto the next one\nDone, done and I’m onto the next one\nDone, done and I’m onto the next one\n\nDone, done and I’m onto the next one\nDone, done and I’m onto the next one\nDone, done and I’m onto the next one\nDone, I’m done and I’m onto the next\n\nDone, done, on to the next one\nDone, I'm done and I'm on to the next one\nDone, done, on to the next one\nDone, I'm done and I'm on to the next\n\nHey, don’t let it go to waste\nI love it but I hate the taste\nWeight keeping me down\n\nHey, don’t let it go to waste\nI love it but I hate the taste\nWeight keeping me down\n\nDone, done, on to the next one\nDone, I'm done and I'm on to the next"


print(lyrics.countWords(string))
print(lyrics.countWords(string2))
print(lyrics.countWords(string3))